### ISSUE TITLE
Port to Bot Users

### ISSUE THREAD

**Issue by wfortin** [Coveo/CoveoSlackBot#25]
https://api.slack.com/bot-users

**Comment by pastjean** [comment]
J'ai starter dequoi pour ca (mais en go par contre)!
[github.com/pastjean/slackbot](https://github.com/pastjean/slackbot)

On a une limite sur les botusers je pense , pas sur les intégration webhook.

Un autre truc qu'on pourrais utiliser c'est [hubot](https://hubot.github.com/),  

c'est vers la que je veux en venir avec mon truc en go. pour l'instant c'est pas un framework de bot mais plus l'implémentation de l'api slack.

Lautre option c'est de créer des users normaux (ca je pense pas qu'on a une limite) (peut-être que les userbot non plus) quoi que 1 ou 2 bots c'est assez

**Comment by pastjean** [comment]
Done ! j'ai fait avec hubot (le code est en js et jai presque tout copié collé) et il y a des millions de plugins avec hubot sur npm!

j'ai presque tout converti no commandes!

https://github.com/pastjean/coveohubot

j'ai un org pour tester dans slack si vous voulez tester, sinon hubot permet de tester en local en faisant simplement `./bin/hubot` @wfortin si tu veux regarder

**Comment by pastjean** [comment]
Done! need to close other bot!
